# Generated by Django 5.2.1 on 2025-05-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], default='researcher', max_length=20),
        ),
    ]
