# Generated by Django 5.2.1 on 2025-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_file_articlefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reference',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reference',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
