# Generated by Django 5.2.1 on 2025-05-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_authors_article_doi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
