# Generated by Django 5.2.1 on 2025-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_summary_articlefile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='linked_excerpt',
            field=models.TextField(blank=True, help_text='The excerpt or section this citation is linked to'),
        ),
    ]
